/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICaseToken,
  ICaseTokenInterface,
} from "../../../contracts/Treasury.sol/ICaseToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICaseToken__factory {
  static readonly abi = _abi;
  static createInterface(): ICaseTokenInterface {
    return new Interface(_abi) as ICaseTokenInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICaseToken {
    return new Contract(address, _abi, runner) as unknown as ICaseToken;
  }
}
